//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3620
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gisis.imo.org/XML/LRIT/pricingFile/2008")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://gisis.imo.org/XML/LRIT/pricingFile/2008", IsNullable=false)]
public partial class PricingFile {
    
    private PricingFilePriceList[] priceListField;
    
    private decimal schemaVersionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PriceList")]
    public PricingFilePriceList[] PriceList {
        get {
            return this.priceListField;
        }
        set {
            this.priceListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal schemaVersion {
        get {
            return this.schemaVersionField;
        }
        set {
            this.schemaVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gisis.imo.org/XML/LRIT/pricingFile/2008")]
public partial class PricingFilePriceList {
    
    private string dataProviderIDField;
    
    private PricingFilePriceListBreakDown[] breakDownField;
    
    private string dataCentreIDField;
    
    private System.DateTime issueDateField;
    
    private bool issueDateFieldSpecified;
    
    private System.DateTime effectiveDateField;
    
    private bool effectiveDateFieldSpecified;
    
    /// <remarks/>
    public string dataProviderID {
        get {
            return this.dataProviderIDField;
        }
        set {
            this.dataProviderIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BreakDown")]
    public PricingFilePriceListBreakDown[] BreakDown {
        get {
            return this.breakDownField;
        }
        set {
            this.breakDownField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataCentreID {
        get {
            return this.dataCentreIDField;
        }
        set {
            this.dataCentreIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime issueDate {
        get {
            return this.issueDateField;
        }
        set {
            this.issueDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool issueDateSpecified {
        get {
            return this.issueDateFieldSpecified;
        }
        set {
            this.issueDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime effectiveDate {
        get {
            return this.effectiveDateField;
        }
        set {
            this.effectiveDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool effectiveDateSpecified {
        get {
            return this.effectiveDateFieldSpecified;
        }
        set {
            this.effectiveDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gisis.imo.org/XML/LRIT/pricingFile/2008")]
public partial class PricingFilePriceListBreakDown {
    
    private float pollField;
    
    private float periodicRateChangeField;
    
    private float positionReportField;
    
    private float archivePositionReportField;
    
    private string currencyField;
    
    /// <remarks/>
    public float Poll {
        get {
            return this.pollField;
        }
        set {
            this.pollField = value;
        }
    }
    
    /// <remarks/>
    public float PeriodicRateChange {
        get {
            return this.periodicRateChangeField;
        }
        set {
            this.periodicRateChangeField = value;
        }
    }
    
    /// <remarks/>
    public float PositionReport {
        get {
            return this.positionReportField;
        }
        set {
            this.positionReportField = value;
        }
    }
    
    /// <remarks/>
    public float ArchivePositionReport {
        get {
            return this.archivePositionReportField;
        }
        set {
            this.archivePositionReportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
}
