//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCenterLogic.DataCenterTypesIDE {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gisis.imo.org/XML/LRIT/2008", ConfigurationName="DataCenterTypesIDE.idePortType")]
    public interface idePortType {
        
        // CODEGEN: Generating message contract since the operation ShipPositionReport is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DataCenterLogic.DataCenterTypesIDE.ShipPositionReportResponse ShipPositionReport(DataCenterLogic.DataCenterTypesIDE.ShipPositionReportRequest request);
        
        // CODEGEN: Generating message contract since the operation ShipPositionRequest is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DataCenterLogic.DataCenterTypesIDE.ShipPositionRequestResponse ShipPositionRequest(DataCenterLogic.DataCenterTypesIDE.ShipPositionRequestRequest request);
        
        // CODEGEN: Generating message contract since the operation SARSURPICRequest is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DataCenterLogic.DataCenterTypesIDE.SARSURPICRequestResponse SARSURPICRequest(DataCenterLogic.DataCenterTypesIDE.SARSURPICRequestRequest request);
        
        // CODEGEN: Generating message contract since the operation Receipt is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DataCenterLogic.DataCenterTypesIDE.ReceiptResponse Receipt(DataCenterLogic.DataCenterTypesIDE.ReceiptRequest request);
        
        // CODEGEN: Generating message contract since the operation SystemStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DataCenterLogic.DataCenterTypesIDE.SystemStatusResponse SystemStatus(DataCenterLogic.DataCenterTypesIDE.SystemStatusRequest request);
        
        // CODEGEN: Generating message contract since the operation JournalReport is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DataCenterLogic.DataCenterTypesIDE.JournalReportResponse JournalReport(DataCenterLogic.DataCenterTypesIDE.JournalReportRequest request);
        
        // CODEGEN: Generating message contract since the operation PricingRequest is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DataCenterLogic.DataCenterTypesIDE.PricingRequestResponse PricingRequest(DataCenterLogic.DataCenterTypesIDE.PricingRequestRequest request);
        
        // CODEGEN: Generating message contract since the operation PricingUpdate is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DataCenterLogic.DataCenterTypesIDE.PricingUpdateResponse PricingUpdate(DataCenterLogic.DataCenterTypesIDE.PricingUpdateRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/positionReport/2008")]
    public partial class ShipPositionReportType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string latitudeField;
        
        private string longitudeField;
        
        private System.DateTime timeStamp1Field;
        
        private string shipborneEquipmentIdField;
        
        private string aSPIdField;
        
        private string cSPIdField;
        
        private messageTypeType messageTypeField;
        
        private string messageIdField;
        
        private string referenceIdField;
        
        private string iMONumField;
        
        private string mMSINumField;
        
        private System.DateTime timeStamp2Field;
        
        private System.DateTime timeStamp3Field;
        
        private string dCIdField;
        
        private System.DateTime timeStamp4Field;
        
        private System.DateTime timeStamp5Field;
        
        private responseTypeType responseTypeField;
        
        private string dataUserRequestorField;
        
        private string shipNameField;
        
        private string dataUserProviderField;
        
        private string dDPVersionNumField;
        
        private testType testField;
        
        private decimal schemaVersionField;
        
        public ShipPositionReportType() {
            this.testField = testType.Item0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime TimeStamp1 {
            get {
                return this.timeStamp1Field;
            }
            set {
                this.timeStamp1Field = value;
                this.RaisePropertyChanged("TimeStamp1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ShipborneEquipmentId {
            get {
                return this.shipborneEquipmentIdField;
            }
            set {
                this.shipborneEquipmentIdField = value;
                this.RaisePropertyChanged("ShipborneEquipmentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ASPId {
            get {
                return this.aSPIdField;
            }
            set {
                this.aSPIdField = value;
                this.RaisePropertyChanged("ASPId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CSPId {
            get {
                return this.cSPIdField;
            }
            set {
                this.cSPIdField = value;
                this.RaisePropertyChanged("CSPId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public messageTypeType MessageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
                this.RaisePropertyChanged("MessageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("MessageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ReferenceId {
            get {
                return this.referenceIdField;
            }
            set {
                this.referenceIdField = value;
                this.RaisePropertyChanged("ReferenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string IMONum {
            get {
                return this.iMONumField;
            }
            set {
                this.iMONumField = value;
                this.RaisePropertyChanged("IMONum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string MMSINum {
            get {
                return this.mMSINumField;
            }
            set {
                this.mMSINumField = value;
                this.RaisePropertyChanged("MMSINum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.DateTime TimeStamp2 {
            get {
                return this.timeStamp2Field;
            }
            set {
                this.timeStamp2Field = value;
                this.RaisePropertyChanged("TimeStamp2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime TimeStamp3 {
            get {
                return this.timeStamp3Field;
            }
            set {
                this.timeStamp3Field = value;
                this.RaisePropertyChanged("TimeStamp3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string DCId {
            get {
                return this.dCIdField;
            }
            set {
                this.dCIdField = value;
                this.RaisePropertyChanged("DCId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public System.DateTime TimeStamp4 {
            get {
                return this.timeStamp4Field;
            }
            set {
                this.timeStamp4Field = value;
                this.RaisePropertyChanged("TimeStamp4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public System.DateTime TimeStamp5 {
            get {
                return this.timeStamp5Field;
            }
            set {
                this.timeStamp5Field = value;
                this.RaisePropertyChanged("TimeStamp5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public responseTypeType ResponseType {
            get {
                return this.responseTypeField;
            }
            set {
                this.responseTypeField = value;
                this.RaisePropertyChanged("ResponseType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string DataUserRequestor {
            get {
                return this.dataUserRequestorField;
            }
            set {
                this.dataUserRequestorField = value;
                this.RaisePropertyChanged("DataUserRequestor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ShipName {
            get {
                return this.shipNameField;
            }
            set {
                this.shipNameField = value;
                this.RaisePropertyChanged("ShipName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string DataUserProvider {
            get {
                return this.dataUserProviderField;
            }
            set {
                this.dataUserProviderField = value;
                this.RaisePropertyChanged("DataUserProvider");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string DDPVersionNum {
            get {
                return this.dDPVersionNumField;
            }
            set {
                this.dDPVersionNumField = value;
                this.RaisePropertyChanged("DDPVersionNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(testType.Item0)]
        public testType test {
            get {
                return this.testField;
            }
            set {
                this.testField = value;
                this.RaisePropertyChanged("test");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal schemaVersion {
            get {
                return this.schemaVersionField;
            }
            set {
                this.schemaVersionField = value;
                this.RaisePropertyChanged("schemaVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/positionReport/2008")]
    public enum messageTypeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/types/2008")]
    public enum responseTypeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/types/2008")]
    public enum testType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/pricingUpdate/2008")]
    public partial class PricingUpdateType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private messageTypeType7 messageTypeField;
        
        private string messageIdField;
        
        private string referenceIdField;
        
        private string messageField;
        
        private System.DateTime timeStampField;
        
        private string dDPVersionNumField;
        
        private byte[] pricingFileField;
        
        private testType testField;
        
        private decimal schemaVersionField;
        
        public PricingUpdateType() {
            this.testField = testType.Item0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public messageTypeType7 MessageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
                this.RaisePropertyChanged("MessageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("MessageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ReferenceId {
            get {
                return this.referenceIdField;
            }
            set {
                this.referenceIdField = value;
                this.RaisePropertyChanged("ReferenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DDPVersionNum {
            get {
                return this.dDPVersionNumField;
            }
            set {
                this.dDPVersionNumField = value;
                this.RaisePropertyChanged("DDPVersionNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=6)]
        public byte[] PricingFile {
            get {
                return this.pricingFileField;
            }
            set {
                this.pricingFileField = value;
                this.RaisePropertyChanged("PricingFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(testType.Item0)]
        public testType test {
            get {
                return this.testField;
            }
            set {
                this.testField = value;
                this.RaisePropertyChanged("test");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal schemaVersion {
            get {
                return this.schemaVersionField;
            }
            set {
                this.schemaVersionField = value;
                this.RaisePropertyChanged("schemaVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="messageTypeType", Namespace="http://gisis.imo.org/XML/LRIT/pricingUpdate/2008")]
    public enum messageTypeType7 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/pricingRequest/2008")]
    public partial class PricingRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private messageTypeType6 messageTypeField;
        
        private string messageIdField;
        
        private string referenceIdField;
        
        private string originatorField;
        
        private System.DateTime timeStampField;
        
        private string dDPVersionNumField;
        
        private testType testField;
        
        private decimal schemaVersionField;
        
        public PricingRequestType() {
            this.testField = testType.Item0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public messageTypeType6 MessageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
                this.RaisePropertyChanged("MessageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("MessageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ReferenceId {
            get {
                return this.referenceIdField;
            }
            set {
                this.referenceIdField = value;
                this.RaisePropertyChanged("ReferenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Originator {
            get {
                return this.originatorField;
            }
            set {
                this.originatorField = value;
                this.RaisePropertyChanged("Originator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DDPVersionNum {
            get {
                return this.dDPVersionNumField;
            }
            set {
                this.dDPVersionNumField = value;
                this.RaisePropertyChanged("DDPVersionNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(testType.Item0)]
        public testType test {
            get {
                return this.testField;
            }
            set {
                this.testField = value;
                this.RaisePropertyChanged("test");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal schemaVersion {
            get {
                return this.schemaVersionField;
            }
            set {
                this.schemaVersionField = value;
                this.RaisePropertyChanged("schemaVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="messageTypeType", Namespace="http://gisis.imo.org/XML/LRIT/pricingRequest/2008")]
    public enum messageTypeType6 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14")]
        Item14,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/journalReport/2008")]
    public partial class JournalReportType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private messageTypeType5 messageTypeField;
        
        private string messageIdField;
        
        private string messageField;
        
        private System.DateTime timeStampField;
        
        private string originatorField;
        
        private byte[] journalFileField;
        
        private string dDPVersionNumField;
        
        private testType testField;
        
        private decimal schemaVersionField;
        
        public JournalReportType() {
            this.testField = testType.Item0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public messageTypeType5 MessageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
                this.RaisePropertyChanged("MessageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("MessageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Originator {
            get {
                return this.originatorField;
            }
            set {
                this.originatorField = value;
                this.RaisePropertyChanged("Originator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=5)]
        public byte[] JournalFile {
            get {
                return this.journalFileField;
            }
            set {
                this.journalFileField = value;
                this.RaisePropertyChanged("JournalFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DDPVersionNum {
            get {
                return this.dDPVersionNumField;
            }
            set {
                this.dDPVersionNumField = value;
                this.RaisePropertyChanged("DDPVersionNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(testType.Item0)]
        public testType test {
            get {
                return this.testField;
            }
            set {
                this.testField = value;
                this.RaisePropertyChanged("test");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal schemaVersion {
            get {
                return this.schemaVersionField;
            }
            set {
                this.schemaVersionField = value;
                this.RaisePropertyChanged("schemaVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="messageTypeType", Namespace="http://gisis.imo.org/XML/LRIT/journalReport/2008")]
    public enum messageTypeType5 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/systemStatus/2008")]
    public partial class SystemStatusType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private messageTypeType4 messageTypeField;
        
        private string messageIdField;
        
        private System.DateTime timeStampField;
        
        private string dDPVersionNumField;
        
        private systemStatusIndicatorType systemStatusField;
        
        private string messageField;
        
        private string originatorField;
        
        private testType testField;
        
        private decimal schemaVersionField;
        
        public SystemStatusType() {
            this.testField = testType.Item0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public messageTypeType4 MessageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
                this.RaisePropertyChanged("MessageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("MessageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DDPVersionNum {
            get {
                return this.dDPVersionNumField;
            }
            set {
                this.dDPVersionNumField = value;
                this.RaisePropertyChanged("DDPVersionNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public systemStatusIndicatorType SystemStatus {
            get {
                return this.systemStatusField;
            }
            set {
                this.systemStatusField = value;
                this.RaisePropertyChanged("SystemStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Originator {
            get {
                return this.originatorField;
            }
            set {
                this.originatorField = value;
                this.RaisePropertyChanged("Originator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(testType.Item0)]
        public testType test {
            get {
                return this.testField;
            }
            set {
                this.testField = value;
                this.RaisePropertyChanged("test");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal schemaVersion {
            get {
                return this.schemaVersionField;
            }
            set {
                this.schemaVersionField = value;
                this.RaisePropertyChanged("schemaVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="messageTypeType", Namespace="http://gisis.imo.org/XML/LRIT/systemStatus/2008")]
    public enum messageTypeType4 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/systemStatus/2008")]
    public enum systemStatusIndicatorType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/receipt/2008")]
    public partial class ReceiptType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private messageTypeType3 messageTypeField;
        
        private string messageIdField;
        
        private string referenceIdField;
        
        private receiptCodeType receiptCodeField;
        
        private string destinationField;
        
        private string originatorField;
        
        private string messageField;
        
        private System.DateTime timeStampField;
        
        private string dDPVersionNumField;
        
        private testType testField;
        
        private decimal schemaVersionField;
        
        public ReceiptType() {
            this.testField = testType.Item0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public messageTypeType3 MessageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
                this.RaisePropertyChanged("MessageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("MessageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ReferenceId {
            get {
                return this.referenceIdField;
            }
            set {
                this.referenceIdField = value;
                this.RaisePropertyChanged("ReferenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public receiptCodeType ReceiptCode {
            get {
                return this.receiptCodeField;
            }
            set {
                this.receiptCodeField = value;
                this.RaisePropertyChanged("ReceiptCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("Destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Originator {
            get {
                return this.originatorField;
            }
            set {
                this.originatorField = value;
                this.RaisePropertyChanged("Originator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string DDPVersionNum {
            get {
                return this.dDPVersionNumField;
            }
            set {
                this.dDPVersionNumField = value;
                this.RaisePropertyChanged("DDPVersionNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(testType.Item0)]
        public testType test {
            get {
                return this.testField;
            }
            set {
                this.testField = value;
                this.RaisePropertyChanged("test");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal schemaVersion {
            get {
                return this.schemaVersionField;
            }
            set {
                this.schemaVersionField = value;
                this.RaisePropertyChanged("schemaVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="messageTypeType", Namespace="http://gisis.imo.org/XML/LRIT/receipt/2008")]
    public enum messageTypeType3 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/receipt/2008")]
    public enum receiptCodeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/sarSurpicRequest/2008")]
    public partial class SARSURPICType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private messageTypeType2 messageTypeField;
        
        private string messageIdField;
        
        private string itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        private string numberOfPositionsField;
        
        private string dataUserRequestorField;
        
        private System.DateTime timeStampField;
        
        private string dDPVersionNumField;
        
        private testType testField;
        
        private decimal schemaVersionField;
        
        public SARSURPICType() {
            this.testField = testType.Item0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public messageTypeType2 MessageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
                this.RaisePropertyChanged("MessageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("MessageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SARCircularArea", typeof(string), Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("SARRectangularArea", typeof(string), Order=2)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=4)]
        public string NumberOfPositions {
            get {
                return this.numberOfPositionsField;
            }
            set {
                this.numberOfPositionsField = value;
                this.RaisePropertyChanged("NumberOfPositions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DataUserRequestor {
            get {
                return this.dataUserRequestorField;
            }
            set {
                this.dataUserRequestorField = value;
                this.RaisePropertyChanged("DataUserRequestor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DDPVersionNum {
            get {
                return this.dDPVersionNumField;
            }
            set {
                this.dDPVersionNumField = value;
                this.RaisePropertyChanged("DDPVersionNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(testType.Item0)]
        public testType test {
            get {
                return this.testField;
            }
            set {
                this.testField = value;
                this.RaisePropertyChanged("test");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal schemaVersion {
            get {
                return this.schemaVersionField;
            }
            set {
                this.schemaVersionField = value;
                this.RaisePropertyChanged("schemaVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="messageTypeType", Namespace="http://gisis.imo.org/XML/LRIT/sarSurpicRequest/2008")]
    public enum messageTypeType2 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/sarSurpicRequest/2008", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        SARCircularArea,
        
        /// <remarks/>
        SARRectangularArea,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/positionRequest/2008")]
    public partial class requestDurationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime startTimeField;
        
        private bool startTimeFieldSpecified;
        
        private System.DateTime stopTimeField;
        
        private bool stopTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime startTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("startTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startTimeSpecified {
            get {
                return this.startTimeFieldSpecified;
            }
            set {
                this.startTimeFieldSpecified = value;
                this.RaisePropertyChanged("startTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime stopTime {
            get {
                return this.stopTimeField;
            }
            set {
                this.stopTimeField = value;
                this.RaisePropertyChanged("stopTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stopTimeSpecified {
            get {
                return this.stopTimeFieldSpecified;
            }
            set {
                this.stopTimeFieldSpecified = value;
                this.RaisePropertyChanged("stopTimeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/positionRequest/2008")]
    public partial class ShipPositionRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private messageTypeType1 messageTypeField;
        
        private string messageIdField;
        
        private string iMONumField;
        
        private string dataUserProviderField;
        
        private accessTypeType accessTypeField;
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private string distanceField;
        
        private requestTypeType requestTypeField;
        
        private requestDurationType requestDurationField;
        
        private string dataUserRequestorField;
        
        private System.DateTime timeStampField;
        
        private string dDPVersionNumField;
        
        private testType testField;
        
        private decimal schemaVersionField;
        
        public ShipPositionRequestType() {
            this.testField = testType.Item0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public messageTypeType1 MessageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
                this.RaisePropertyChanged("MessageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("MessageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IMONum {
            get {
                return this.iMONumField;
            }
            set {
                this.iMONumField = value;
                this.RaisePropertyChanged("IMONum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DataUserProvider {
            get {
                return this.dataUserProviderField;
            }
            set {
                this.dataUserProviderField = value;
                this.RaisePropertyChanged("DataUserProvider");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public accessTypeType AccessType {
            get {
                return this.accessTypeField;
            }
            set {
                this.accessTypeField = value;
                this.RaisePropertyChanged("AccessType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Place", typeof(string), Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("Port", typeof(string), Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("PortFacility", typeof(string), Order=5)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=7)]
        public string Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
                this.RaisePropertyChanged("Distance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public requestTypeType RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
                this.RaisePropertyChanged("RequestType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public requestDurationType RequestDuration {
            get {
                return this.requestDurationField;
            }
            set {
                this.requestDurationField = value;
                this.RaisePropertyChanged("RequestDuration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string DataUserRequestor {
            get {
                return this.dataUserRequestorField;
            }
            set {
                this.dataUserRequestorField = value;
                this.RaisePropertyChanged("DataUserRequestor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DDPVersionNum {
            get {
                return this.dDPVersionNumField;
            }
            set {
                this.dDPVersionNumField = value;
                this.RaisePropertyChanged("DDPVersionNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(testType.Item0)]
        public testType test {
            get {
                return this.testField;
            }
            set {
                this.testField = value;
                this.RaisePropertyChanged("test");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal schemaVersion {
            get {
                return this.schemaVersionField;
            }
            set {
                this.schemaVersionField = value;
                this.RaisePropertyChanged("schemaVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="messageTypeType", Namespace="http://gisis.imo.org/XML/LRIT/positionRequest/2008")]
    public enum messageTypeType1 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/positionRequest/2008")]
    public enum accessTypeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/positionRequest/2008", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        Place,
        
        /// <remarks/>
        Port,
        
        /// <remarks/>
        PortFacility,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/positionRequest/2008")]
    public enum requestTypeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gisis.imo.org/XML/LRIT/2008")]
    public partial class Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private responseType responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public responseType response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("response");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/2008")]
    public enum responseType {
        
        /// <remarks/>
        Success,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShipPositionReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gisis.imo.org/XML/LRIT/positionReport/2008", Order=0)]
        public DataCenterLogic.DataCenterTypesIDE.ShipPositionReportType ShipPositionReport;
        
        public ShipPositionReportRequest() {
        }
        
        public ShipPositionReportRequest(DataCenterLogic.DataCenterTypesIDE.ShipPositionReportType ShipPositionReport) {
            this.ShipPositionReport = ShipPositionReport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShipPositionReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gisis.imo.org/XML/LRIT/2008", Order=0)]
        public DataCenterLogic.DataCenterTypesIDE.Response Response;
        
        public ShipPositionReportResponse() {
        }
        
        public ShipPositionReportResponse(DataCenterLogic.DataCenterTypesIDE.Response Response) {
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShipPositionRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gisis.imo.org/XML/LRIT/positionRequest/2008", Order=0)]
        public DataCenterLogic.DataCenterTypesIDE.ShipPositionRequestType ShipPositionRequest;
        
        public ShipPositionRequestRequest() {
        }
        
        public ShipPositionRequestRequest(DataCenterLogic.DataCenterTypesIDE.ShipPositionRequestType ShipPositionRequest) {
            this.ShipPositionRequest = ShipPositionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShipPositionRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gisis.imo.org/XML/LRIT/2008", Order=0)]
        public DataCenterLogic.DataCenterTypesIDE.Response Response;
        
        public ShipPositionRequestResponse() {
        }
        
        public ShipPositionRequestResponse(DataCenterLogic.DataCenterTypesIDE.Response Response) {
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SARSURPICRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gisis.imo.org/XML/LRIT/sarSurpicRequest/2008", Order=0)]
        public DataCenterLogic.DataCenterTypesIDE.SARSURPICType SARSURPICRequest;
        
        public SARSURPICRequestRequest() {
        }
        
        public SARSURPICRequestRequest(DataCenterLogic.DataCenterTypesIDE.SARSURPICType SARSURPICRequest) {
            this.SARSURPICRequest = SARSURPICRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SARSURPICRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gisis.imo.org/XML/LRIT/2008", Order=0)]
        public DataCenterLogic.DataCenterTypesIDE.Response Response;
        
        public SARSURPICRequestResponse() {
        }
        
        public SARSURPICRequestResponse(DataCenterLogic.DataCenterTypesIDE.Response Response) {
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gisis.imo.org/XML/LRIT/receipt/2008", Order=0)]
        public DataCenterLogic.DataCenterTypesIDE.ReceiptType Receipt;
        
        public ReceiptRequest() {
        }
        
        public ReceiptRequest(DataCenterLogic.DataCenterTypesIDE.ReceiptType Receipt) {
            this.Receipt = Receipt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gisis.imo.org/XML/LRIT/2008", Order=0)]
        public DataCenterLogic.DataCenterTypesIDE.Response Response;
        
        public ReceiptResponse() {
        }
        
        public ReceiptResponse(DataCenterLogic.DataCenterTypesIDE.Response Response) {
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SystemStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gisis.imo.org/XML/LRIT/systemStatus/2008", Order=0)]
        public DataCenterLogic.DataCenterTypesIDE.SystemStatusType SystemStatus;
        
        public SystemStatusRequest() {
        }
        
        public SystemStatusRequest(DataCenterLogic.DataCenterTypesIDE.SystemStatusType SystemStatus) {
            this.SystemStatus = SystemStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SystemStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gisis.imo.org/XML/LRIT/2008", Order=0)]
        public DataCenterLogic.DataCenterTypesIDE.Response Response;
        
        public SystemStatusResponse() {
        }
        
        public SystemStatusResponse(DataCenterLogic.DataCenterTypesIDE.Response Response) {
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JournalReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gisis.imo.org/XML/LRIT/journalReport/2008", Order=0)]
        public DataCenterLogic.DataCenterTypesIDE.JournalReportType JournalReport;
        
        public JournalReportRequest() {
        }
        
        public JournalReportRequest(DataCenterLogic.DataCenterTypesIDE.JournalReportType JournalReport) {
            this.JournalReport = JournalReport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JournalReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gisis.imo.org/XML/LRIT/2008", Order=0)]
        public DataCenterLogic.DataCenterTypesIDE.Response Response;
        
        public JournalReportResponse() {
        }
        
        public JournalReportResponse(DataCenterLogic.DataCenterTypesIDE.Response Response) {
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PricingRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gisis.imo.org/XML/LRIT/pricingRequest/2008", Order=0)]
        public DataCenterLogic.DataCenterTypesIDE.PricingRequestType PricingRequest;
        
        public PricingRequestRequest() {
        }
        
        public PricingRequestRequest(DataCenterLogic.DataCenterTypesIDE.PricingRequestType PricingRequest) {
            this.PricingRequest = PricingRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PricingRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gisis.imo.org/XML/LRIT/2008", Order=0)]
        public DataCenterLogic.DataCenterTypesIDE.Response Response;
        
        public PricingRequestResponse() {
        }
        
        public PricingRequestResponse(DataCenterLogic.DataCenterTypesIDE.Response Response) {
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PricingUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gisis.imo.org/XML/LRIT/pricingUpdate/2008", Order=0)]
        public DataCenterLogic.DataCenterTypesIDE.PricingUpdateType PricingUpdate;
        
        public PricingUpdateRequest() {
        }
        
        public PricingUpdateRequest(DataCenterLogic.DataCenterTypesIDE.PricingUpdateType PricingUpdate) {
            this.PricingUpdate = PricingUpdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PricingUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gisis.imo.org/XML/LRIT/2008", Order=0)]
        public DataCenterLogic.DataCenterTypesIDE.Response Response;
        
        public PricingUpdateResponse() {
        }
        
        public PricingUpdateResponse(DataCenterLogic.DataCenterTypesIDE.Response Response) {
            this.Response = Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface idePortTypeChannel : DataCenterLogic.DataCenterTypesIDE.idePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class idePortTypeClient : System.ServiceModel.ClientBase<DataCenterLogic.DataCenterTypesIDE.idePortType>, DataCenterLogic.DataCenterTypesIDE.idePortType {
        
        public idePortTypeClient() {
        }
        
        public idePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public idePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public idePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public idePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataCenterLogic.DataCenterTypesIDE.ShipPositionReportResponse DataCenterLogic.DataCenterTypesIDE.idePortType.ShipPositionReport(DataCenterLogic.DataCenterTypesIDE.ShipPositionReportRequest request) {
            return base.Channel.ShipPositionReport(request);
        }
        
        public DataCenterLogic.DataCenterTypesIDE.Response ShipPositionReport(DataCenterLogic.DataCenterTypesIDE.ShipPositionReportType ShipPositionReport1) {
            DataCenterLogic.DataCenterTypesIDE.ShipPositionReportRequest inValue = new DataCenterLogic.DataCenterTypesIDE.ShipPositionReportRequest();
            inValue.ShipPositionReport = ShipPositionReport1;
            DataCenterLogic.DataCenterTypesIDE.ShipPositionReportResponse retVal = ((DataCenterLogic.DataCenterTypesIDE.idePortType)(this)).ShipPositionReport(inValue);
            return retVal.Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataCenterLogic.DataCenterTypesIDE.ShipPositionRequestResponse DataCenterLogic.DataCenterTypesIDE.idePortType.ShipPositionRequest(DataCenterLogic.DataCenterTypesIDE.ShipPositionRequestRequest request) {
            return base.Channel.ShipPositionRequest(request);
        }
        
        public DataCenterLogic.DataCenterTypesIDE.Response ShipPositionRequest(DataCenterLogic.DataCenterTypesIDE.ShipPositionRequestType ShipPositionRequest1) {
            DataCenterLogic.DataCenterTypesIDE.ShipPositionRequestRequest inValue = new DataCenterLogic.DataCenterTypesIDE.ShipPositionRequestRequest();
            inValue.ShipPositionRequest = ShipPositionRequest1;
            DataCenterLogic.DataCenterTypesIDE.ShipPositionRequestResponse retVal = ((DataCenterLogic.DataCenterTypesIDE.idePortType)(this)).ShipPositionRequest(inValue);
            return retVal.Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataCenterLogic.DataCenterTypesIDE.SARSURPICRequestResponse DataCenterLogic.DataCenterTypesIDE.idePortType.SARSURPICRequest(DataCenterLogic.DataCenterTypesIDE.SARSURPICRequestRequest request) {
            return base.Channel.SARSURPICRequest(request);
        }
        
        public DataCenterLogic.DataCenterTypesIDE.Response SARSURPICRequest(DataCenterLogic.DataCenterTypesIDE.SARSURPICType SARSURPICRequest1) {
            DataCenterLogic.DataCenterTypesIDE.SARSURPICRequestRequest inValue = new DataCenterLogic.DataCenterTypesIDE.SARSURPICRequestRequest();
            inValue.SARSURPICRequest = SARSURPICRequest1;
            DataCenterLogic.DataCenterTypesIDE.SARSURPICRequestResponse retVal = ((DataCenterLogic.DataCenterTypesIDE.idePortType)(this)).SARSURPICRequest(inValue);
            return retVal.Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataCenterLogic.DataCenterTypesIDE.ReceiptResponse DataCenterLogic.DataCenterTypesIDE.idePortType.Receipt(DataCenterLogic.DataCenterTypesIDE.ReceiptRequest request) {
            return base.Channel.Receipt(request);
        }
        
        public DataCenterLogic.DataCenterTypesIDE.Response Receipt(DataCenterLogic.DataCenterTypesIDE.ReceiptType Receipt1) {
            DataCenterLogic.DataCenterTypesIDE.ReceiptRequest inValue = new DataCenterLogic.DataCenterTypesIDE.ReceiptRequest();
            inValue.Receipt = Receipt1;
            DataCenterLogic.DataCenterTypesIDE.ReceiptResponse retVal = ((DataCenterLogic.DataCenterTypesIDE.idePortType)(this)).Receipt(inValue);
            return retVal.Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataCenterLogic.DataCenterTypesIDE.SystemStatusResponse DataCenterLogic.DataCenterTypesIDE.idePortType.SystemStatus(DataCenterLogic.DataCenterTypesIDE.SystemStatusRequest request) {
            return base.Channel.SystemStatus(request);
        }
        
        public DataCenterLogic.DataCenterTypesIDE.Response SystemStatus(DataCenterLogic.DataCenterTypesIDE.SystemStatusType SystemStatus1) {
            DataCenterLogic.DataCenterTypesIDE.SystemStatusRequest inValue = new DataCenterLogic.DataCenterTypesIDE.SystemStatusRequest();
            inValue.SystemStatus = SystemStatus1;
            DataCenterLogic.DataCenterTypesIDE.SystemStatusResponse retVal = ((DataCenterLogic.DataCenterTypesIDE.idePortType)(this)).SystemStatus(inValue);
            return retVal.Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataCenterLogic.DataCenterTypesIDE.JournalReportResponse DataCenterLogic.DataCenterTypesIDE.idePortType.JournalReport(DataCenterLogic.DataCenterTypesIDE.JournalReportRequest request) {
            return base.Channel.JournalReport(request);
        }
        
        public DataCenterLogic.DataCenterTypesIDE.Response JournalReport(DataCenterLogic.DataCenterTypesIDE.JournalReportType JournalReport1) {
            DataCenterLogic.DataCenterTypesIDE.JournalReportRequest inValue = new DataCenterLogic.DataCenterTypesIDE.JournalReportRequest();
            inValue.JournalReport = JournalReport1;
            DataCenterLogic.DataCenterTypesIDE.JournalReportResponse retVal = ((DataCenterLogic.DataCenterTypesIDE.idePortType)(this)).JournalReport(inValue);
            return retVal.Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataCenterLogic.DataCenterTypesIDE.PricingRequestResponse DataCenterLogic.DataCenterTypesIDE.idePortType.PricingRequest(DataCenterLogic.DataCenterTypesIDE.PricingRequestRequest request) {
            return base.Channel.PricingRequest(request);
        }
        
        public DataCenterLogic.DataCenterTypesIDE.Response PricingRequest(DataCenterLogic.DataCenterTypesIDE.PricingRequestType PricingRequest1) {
            DataCenterLogic.DataCenterTypesIDE.PricingRequestRequest inValue = new DataCenterLogic.DataCenterTypesIDE.PricingRequestRequest();
            inValue.PricingRequest = PricingRequest1;
            DataCenterLogic.DataCenterTypesIDE.PricingRequestResponse retVal = ((DataCenterLogic.DataCenterTypesIDE.idePortType)(this)).PricingRequest(inValue);
            return retVal.Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataCenterLogic.DataCenterTypesIDE.PricingUpdateResponse DataCenterLogic.DataCenterTypesIDE.idePortType.PricingUpdate(DataCenterLogic.DataCenterTypesIDE.PricingUpdateRequest request) {
            return base.Channel.PricingUpdate(request);
        }
        
        public DataCenterLogic.DataCenterTypesIDE.Response PricingUpdate(DataCenterLogic.DataCenterTypesIDE.PricingUpdateType PricingUpdate1) {
            DataCenterLogic.DataCenterTypesIDE.PricingUpdateRequest inValue = new DataCenterLogic.DataCenterTypesIDE.PricingUpdateRequest();
            inValue.PricingUpdate = PricingUpdate1;
            DataCenterLogic.DataCenterTypesIDE.PricingUpdateResponse retVal = ((DataCenterLogic.DataCenterTypesIDE.idePortType)(this)).PricingUpdate(inValue);
            return retVal.Response;
        }
    }
}
