//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LRITSIGOTestClient.LRITSIGO {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.ws.prefecturanaval.gov.ar/LRITSIGO/", ConfigurationName="LRITSIGO.LRITSIGOSoap")]
    public interface LRITSIGOSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.ws.prefecturanaval.gov.ar/LRITSIGO/DatasetLrit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet DatasetLrit();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.ws.prefecturanaval.gov.ar/LRITSIGO/DatasetLritHistorico", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet DatasetLritHistorico(System.DateTime fromDate, System.DateTime toDate, string[] shipIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.ws.prefecturanaval.gov.ar/LRITSIGO/DatasetLrit_ContractingGoverment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet DatasetLrit_ContractingGoverment();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.ws.prefecturanaval.gov.ar/LRITSIGO/DatasetLritFlitro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet DatasetLritFlitro(string mmsi, string matricula, string nro_omi, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.ws.prefecturanaval.gov.ar/LRITSIGO/DatasetLritSt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet DatasetLritSt();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.ws.prefecturanaval.gov.ar/LRITSIGO/DatasetLritStFiltro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet DatasetLritStFiltro(string ShipName, string IMONum, string MMSINum);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.ws.prefecturanaval.gov.ar/LRITSIGO/DatasetLritPort_id", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet DatasetLritPort_id(int LRITid);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.ws.prefecturanaval.gov.ar/LRITSIGO/DatasetLritPort_name", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet DatasetLritPort_name(string Name_Place);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.ws.prefecturanaval.gov.ar/LRITSIGO/DatasetLritPort_facility_id", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet DatasetLritPort_facility_id(int LRITid);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.ws.prefecturanaval.gov.ar/LRITSIGO/DatasetLritDDP1000mn_id", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet DatasetLritDDP1000mn_id(int LRITid);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.ws.prefecturanaval.gov.ar/LRITSIGO/DatasetLRIT_SIGO_TERRITORIAL_SEA_i" +
            "d", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet DatasetLRIT_SIGO_TERRITORIAL_SEA_id(int LRITid);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.ws.prefecturanaval.gov.ar/LRITSIGO/DatasetLritDDP_LRIT_SIGO_INTERNAL_" +
            "WATER_ID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet DatasetLritDDP_LRIT_SIGO_INTERNAL_WATER_ID(int LRITid);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.ws.prefecturanaval.gov.ar/LRITSIGO/DatasetLritDDP_CUSTOM_COASTAL_AREA" +
            "S_ID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet DatasetLritDDP_CUSTOM_COASTAL_AREAS_ID(int LRITid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface LRITSIGOSoapChannel : LRITSIGOTestClient.LRITSIGO.LRITSIGOSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class LRITSIGOSoapClient : System.ServiceModel.ClientBase<LRITSIGOTestClient.LRITSIGO.LRITSIGOSoap>, LRITSIGOTestClient.LRITSIGO.LRITSIGOSoap {
        
        public LRITSIGOSoapClient() {
        }
        
        public LRITSIGOSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LRITSIGOSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LRITSIGOSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LRITSIGOSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet DatasetLrit() {
            return base.Channel.DatasetLrit();
        }
        
        public System.Data.DataSet DatasetLritHistorico(System.DateTime fromDate, System.DateTime toDate, string[] shipIds) {
            return base.Channel.DatasetLritHistorico(fromDate, toDate, shipIds);
        }
        
        public System.Data.DataSet DatasetLrit_ContractingGoverment() {
            return base.Channel.DatasetLrit_ContractingGoverment();
        }
        
        public System.Data.DataSet DatasetLritFlitro(string mmsi, string matricula, string nro_omi, string nombre) {
            return base.Channel.DatasetLritFlitro(mmsi, matricula, nro_omi, nombre);
        }
        
        public System.Data.DataSet DatasetLritSt() {
            return base.Channel.DatasetLritSt();
        }
        
        public System.Data.DataSet DatasetLritStFiltro(string ShipName, string IMONum, string MMSINum) {
            return base.Channel.DatasetLritStFiltro(ShipName, IMONum, MMSINum);
        }
        
        public System.Data.DataSet DatasetLritPort_id(int LRITid) {
            return base.Channel.DatasetLritPort_id(LRITid);
        }
        
        public System.Data.DataSet DatasetLritPort_name(string Name_Place) {
            return base.Channel.DatasetLritPort_name(Name_Place);
        }
        
        public System.Data.DataSet DatasetLritPort_facility_id(int LRITid) {
            return base.Channel.DatasetLritPort_facility_id(LRITid);
        }
        
        public System.Data.DataSet DatasetLritDDP1000mn_id(int LRITid) {
            return base.Channel.DatasetLritDDP1000mn_id(LRITid);
        }
        
        public System.Data.DataSet DatasetLRIT_SIGO_TERRITORIAL_SEA_id(int LRITid) {
            return base.Channel.DatasetLRIT_SIGO_TERRITORIAL_SEA_id(LRITid);
        }
        
        public System.Data.DataSet DatasetLritDDP_LRIT_SIGO_INTERNAL_WATER_ID(int LRITid) {
            return base.Channel.DatasetLritDDP_LRIT_SIGO_INTERNAL_WATER_ID(LRITid);
        }
        
        public System.Data.DataSet DatasetLritDDP_CUSTOM_COASTAL_AREAS_ID(int LRITid) {
            return base.Channel.DatasetLritDDP_CUSTOM_COASTAL_AREAS_ID(LRITid);
        }
    }
}
