//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Web.Services.WebServiceBindingAttribute(Name="ideServiceBinding", Namespace="http://gisis.imo.org/XML/LRIT/2008")]
public interface IIdeServiceBinding {
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("Response", Namespace="http://gisis.imo.org/XML/LRIT/2008")]
    Response ShipPositionReport([System.Xml.Serialization.XmlElementAttribute("ShipPositionReport", Namespace="http://gisis.imo.org/XML/LRIT/positionReport/2008")] ShipPositionReportType ShipPositionReport1);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("Response", Namespace="http://gisis.imo.org/XML/LRIT/2008")]
    Response ShipPositionRequest([System.Xml.Serialization.XmlElementAttribute("ShipPositionRequest", Namespace="http://gisis.imo.org/XML/LRIT/positionRequest/2008")] ShipPositionRequestType ShipPositionRequest1);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("Response", Namespace="http://gisis.imo.org/XML/LRIT/2008")]
    Response SARSURPICRequest([System.Xml.Serialization.XmlElementAttribute("SARSURPICRequest", Namespace="http://gisis.imo.org/XML/LRIT/sarSurpicRequest/2008")] SARSURPICType SARSURPICRequest1);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("Response", Namespace="http://gisis.imo.org/XML/LRIT/2008")]
    Response Receipt([System.Xml.Serialization.XmlElementAttribute("Receipt", Namespace="http://gisis.imo.org/XML/LRIT/receipt/2008")] ReceiptType Receipt1);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("Response", Namespace="http://gisis.imo.org/XML/LRIT/2008")]
    Response SystemStatus([System.Xml.Serialization.XmlElementAttribute("SystemStatus", Namespace="http://gisis.imo.org/XML/LRIT/systemStatus/2008")] SystemStatusType SystemStatus1);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("Response", Namespace="http://gisis.imo.org/XML/LRIT/2008")]
    Response JournalReport([System.Xml.Serialization.XmlElementAttribute("JournalReport", Namespace="http://gisis.imo.org/XML/LRIT/journalReport/2008")] JournalReportType JournalReport1);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("Response", Namespace="http://gisis.imo.org/XML/LRIT/2008")]
    Response PricingRequest([System.Xml.Serialization.XmlElementAttribute("PricingRequest", Namespace="http://gisis.imo.org/XML/LRIT/pricingRequest/2008")] PricingRequestType PricingRequest1);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("Response", Namespace="http://gisis.imo.org/XML/LRIT/2008")]
    Response PricingUpdate([System.Xml.Serialization.XmlElementAttribute("PricingUpdate", Namespace="http://gisis.imo.org/XML/LRIT/pricingUpdate/2008")] PricingUpdateType PricingUpdate1);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/positionReport/2008")]
public partial class ShipPositionReportType {
    
    private string latitudeField;
    
    private string longitudeField;
    
    private System.DateTime timeStamp1Field;
    
    private string shipborneEquipmentIdField;
    
    private string aSPIdField;
    
    private string cSPIdField;
    
    private messageTypeType messageTypeField;
    
    private string messageIdField;
    
    private string referenceIdField;
    
    private string iMONumField;
    
    private string mMSINumField;
    
    private System.DateTime timeStamp2Field;
    
    private System.DateTime timeStamp3Field;
    
    private string dCIdField;
    
    private System.DateTime timeStamp4Field;
    
    private System.DateTime timeStamp5Field;
    
    private responseTypeType responseTypeField;
    
    private string dataUserRequestorField;
    
    private string shipNameField;
    
    private string dataUserProviderField;
    
    private string dDPVersionNumField;
    
    private testType testField;
    
    private decimal schemaVersionField;
    
    public ShipPositionReportType() {
        this.testField = testType.Item0;
    }
    
    /// <remarks/>
    public string Latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    public string Longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TimeStamp1 {
        get {
            return this.timeStamp1Field;
        }
        set {
            this.timeStamp1Field = value;
        }
    }
    
    /// <remarks/>
    public string ShipborneEquipmentId {
        get {
            return this.shipborneEquipmentIdField;
        }
        set {
            this.shipborneEquipmentIdField = value;
        }
    }
    
    /// <remarks/>
    public string ASPId {
        get {
            return this.aSPIdField;
        }
        set {
            this.aSPIdField = value;
        }
    }
    
    /// <remarks/>
    public string CSPId {
        get {
            return this.cSPIdField;
        }
        set {
            this.cSPIdField = value;
        }
    }
    
    /// <remarks/>
    public messageTypeType MessageType {
        get {
            return this.messageTypeField;
        }
        set {
            this.messageTypeField = value;
        }
    }
    
    /// <remarks/>
    public string MessageId {
        get {
            return this.messageIdField;
        }
        set {
            this.messageIdField = value;
        }
    }
    
    /// <remarks/>
    public string ReferenceId {
        get {
            return this.referenceIdField;
        }
        set {
            this.referenceIdField = value;
        }
    }
    
    /// <remarks/>
    public string IMONum {
        get {
            return this.iMONumField;
        }
        set {
            this.iMONumField = value;
        }
    }
    
    /// <remarks/>
    public string MMSINum {
        get {
            return this.mMSINumField;
        }
        set {
            this.mMSINumField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TimeStamp2 {
        get {
            return this.timeStamp2Field;
        }
        set {
            this.timeStamp2Field = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TimeStamp3 {
        get {
            return this.timeStamp3Field;
        }
        set {
            this.timeStamp3Field = value;
        }
    }
    
    /// <remarks/>
    public string DCId {
        get {
            return this.dCIdField;
        }
        set {
            this.dCIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TimeStamp4 {
        get {
            return this.timeStamp4Field;
        }
        set {
            this.timeStamp4Field = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TimeStamp5 {
        get {
            return this.timeStamp5Field;
        }
        set {
            this.timeStamp5Field = value;
        }
    }
    
    /// <remarks/>
    public responseTypeType ResponseType {
        get {
            return this.responseTypeField;
        }
        set {
            this.responseTypeField = value;
        }
    }
    
    /// <remarks/>
    public string DataUserRequestor {
        get {
            return this.dataUserRequestorField;
        }
        set {
            this.dataUserRequestorField = value;
        }
    }
    
    /// <remarks/>
    public string ShipName {
        get {
            return this.shipNameField;
        }
        set {
            this.shipNameField = value;
        }
    }
    
    /// <remarks/>
    public string DataUserProvider {
        get {
            return this.dataUserProviderField;
        }
        set {
            this.dataUserProviderField = value;
        }
    }
    
    /// <remarks/>
    public string DDPVersionNum {
        get {
            return this.dDPVersionNumField;
        }
        set {
            this.dDPVersionNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(testType.Item0)]
    public testType test {
        get {
            return this.testField;
        }
        set {
            this.testField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal schemaVersion {
        get {
            return this.schemaVersionField;
        }
        set {
            this.schemaVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/positionReport/2008")]
public enum messageTypeType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/types/2008")]
public enum responseTypeType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/types/2008")]
public enum testType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/pricingUpdate/2008")]
public partial class PricingUpdateType {
    
    private messageTypeType7 messageTypeField;
    
    private string messageIdField;
    
    private string referenceIdField;
    
    private string messageField;
    
    private System.DateTime timeStampField;
    
    private string dDPVersionNumField;
    
    private byte[] pricingFileField;
    
    private testType testField;
    
    private decimal schemaVersionField;
    
    public PricingUpdateType() {
        this.testField = testType.Item0;
    }
    
    /// <remarks/>
    public messageTypeType7 MessageType {
        get {
            return this.messageTypeField;
        }
        set {
            this.messageTypeField = value;
        }
    }
    
    /// <remarks/>
    public string MessageId {
        get {
            return this.messageIdField;
        }
        set {
            this.messageIdField = value;
        }
    }
    
    /// <remarks/>
    public string ReferenceId {
        get {
            return this.referenceIdField;
        }
        set {
            this.referenceIdField = value;
        }
    }
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TimeStamp {
        get {
            return this.timeStampField;
        }
        set {
            this.timeStampField = value;
        }
    }
    
    /// <remarks/>
    public string DDPVersionNum {
        get {
            return this.dDPVersionNumField;
        }
        set {
            this.dDPVersionNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] PricingFile {
        get {
            return this.pricingFileField;
        }
        set {
            this.pricingFileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(testType.Item0)]
    public testType test {
        get {
            return this.testField;
        }
        set {
            this.testField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal schemaVersion {
        get {
            return this.schemaVersionField;
        }
        set {
            this.schemaVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="messageTypeType", Namespace="http://gisis.imo.org/XML/LRIT/pricingUpdate/2008")]
public enum messageTypeType7 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("15")]
    Item15,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/pricingRequest/2008")]
public partial class PricingRequestType {
    
    private messageTypeType6 messageTypeField;
    
    private string messageIdField;
    
    private string referenceIdField;
    
    private string originatorField;
    
    private System.DateTime timeStampField;
    
    private string dDPVersionNumField;
    
    private testType testField;
    
    private decimal schemaVersionField;
    
    public PricingRequestType() {
        this.testField = testType.Item0;
    }
    
    /// <remarks/>
    public messageTypeType6 MessageType {
        get {
            return this.messageTypeField;
        }
        set {
            this.messageTypeField = value;
        }
    }
    
    /// <remarks/>
    public string MessageId {
        get {
            return this.messageIdField;
        }
        set {
            this.messageIdField = value;
        }
    }
    
    /// <remarks/>
    public string ReferenceId {
        get {
            return this.referenceIdField;
        }
        set {
            this.referenceIdField = value;
        }
    }
    
    /// <remarks/>
    public string Originator {
        get {
            return this.originatorField;
        }
        set {
            this.originatorField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TimeStamp {
        get {
            return this.timeStampField;
        }
        set {
            this.timeStampField = value;
        }
    }
    
    /// <remarks/>
    public string DDPVersionNum {
        get {
            return this.dDPVersionNumField;
        }
        set {
            this.dDPVersionNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(testType.Item0)]
    public testType test {
        get {
            return this.testField;
        }
        set {
            this.testField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal schemaVersion {
        get {
            return this.schemaVersionField;
        }
        set {
            this.schemaVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="messageTypeType", Namespace="http://gisis.imo.org/XML/LRIT/pricingRequest/2008")]
public enum messageTypeType6 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("14")]
    Item14,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/journalReport/2008")]
public partial class JournalReportType {
    
    private messageTypeType5 messageTypeField;
    
    private string messageIdField;
    
    private string messageField;
    
    private System.DateTime timeStampField;
    
    private string originatorField;
    
    private byte[] journalFileField;
    
    private string dDPVersionNumField;
    
    private testType testField;
    
    private decimal schemaVersionField;
    
    public JournalReportType() {
        this.testField = testType.Item0;
    }
    
    /// <remarks/>
    public messageTypeType5 MessageType {
        get {
            return this.messageTypeField;
        }
        set {
            this.messageTypeField = value;
        }
    }
    
    /// <remarks/>
    public string MessageId {
        get {
            return this.messageIdField;
        }
        set {
            this.messageIdField = value;
        }
    }
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TimeStamp {
        get {
            return this.timeStampField;
        }
        set {
            this.timeStampField = value;
        }
    }
    
    /// <remarks/>
    public string Originator {
        get {
            return this.originatorField;
        }
        set {
            this.originatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] JournalFile {
        get {
            return this.journalFileField;
        }
        set {
            this.journalFileField = value;
        }
    }
    
    /// <remarks/>
    public string DDPVersionNum {
        get {
            return this.dDPVersionNumField;
        }
        set {
            this.dDPVersionNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(testType.Item0)]
    public testType test {
        get {
            return this.testField;
        }
        set {
            this.testField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal schemaVersion {
        get {
            return this.schemaVersionField;
        }
        set {
            this.schemaVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="messageTypeType", Namespace="http://gisis.imo.org/XML/LRIT/journalReport/2008")]
public enum messageTypeType5 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("12")]
    Item12,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/systemStatus/2008")]
public partial class SystemStatusType {
    
    private messageTypeType4 messageTypeField;
    
    private string messageIdField;
    
    private System.DateTime timeStampField;
    
    private string dDPVersionNumField;
    
    private systemStatusIndicatorType systemStatusField;
    
    private string messageField;
    
    private string originatorField;
    
    private testType testField;
    
    private decimal schemaVersionField;
    
    public SystemStatusType() {
        this.testField = testType.Item0;
    }
    
    /// <remarks/>
    public messageTypeType4 MessageType {
        get {
            return this.messageTypeField;
        }
        set {
            this.messageTypeField = value;
        }
    }
    
    /// <remarks/>
    public string MessageId {
        get {
            return this.messageIdField;
        }
        set {
            this.messageIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TimeStamp {
        get {
            return this.timeStampField;
        }
        set {
            this.timeStampField = value;
        }
    }
    
    /// <remarks/>
    public string DDPVersionNum {
        get {
            return this.dDPVersionNumField;
        }
        set {
            this.dDPVersionNumField = value;
        }
    }
    
    /// <remarks/>
    public systemStatusIndicatorType SystemStatus {
        get {
            return this.systemStatusField;
        }
        set {
            this.systemStatusField = value;
        }
    }
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    public string Originator {
        get {
            return this.originatorField;
        }
        set {
            this.originatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(testType.Item0)]
    public testType test {
        get {
            return this.testField;
        }
        set {
            this.testField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal schemaVersion {
        get {
            return this.schemaVersionField;
        }
        set {
            this.schemaVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="messageTypeType", Namespace="http://gisis.imo.org/XML/LRIT/systemStatus/2008")]
public enum messageTypeType4 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("11")]
    Item11,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/systemStatus/2008")]
public enum systemStatusIndicatorType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/receipt/2008")]
public partial class ReceiptType {
    
    private messageTypeType3 messageTypeField;
    
    private string messageIdField;
    
    private string referenceIdField;
    
    private receiptCodeType receiptCodeField;
    
    private string destinationField;
    
    private string originatorField;
    
    private string messageField;
    
    private System.DateTime timeStampField;
    
    private string dDPVersionNumField;
    
    private testType testField;
    
    private decimal schemaVersionField;
    
    public ReceiptType() {
        this.testField = testType.Item0;
    }
    
    /// <remarks/>
    public messageTypeType3 MessageType {
        get {
            return this.messageTypeField;
        }
        set {
            this.messageTypeField = value;
        }
    }
    
    /// <remarks/>
    public string MessageId {
        get {
            return this.messageIdField;
        }
        set {
            this.messageIdField = value;
        }
    }
    
    /// <remarks/>
    public string ReferenceId {
        get {
            return this.referenceIdField;
        }
        set {
            this.referenceIdField = value;
        }
    }
    
    /// <remarks/>
    public receiptCodeType ReceiptCode {
        get {
            return this.receiptCodeField;
        }
        set {
            this.receiptCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Destination {
        get {
            return this.destinationField;
        }
        set {
            this.destinationField = value;
        }
    }
    
    /// <remarks/>
    public string Originator {
        get {
            return this.originatorField;
        }
        set {
            this.originatorField = value;
        }
    }
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TimeStamp {
        get {
            return this.timeStampField;
        }
        set {
            this.timeStampField = value;
        }
    }
    
    /// <remarks/>
    public string DDPVersionNum {
        get {
            return this.dDPVersionNumField;
        }
        set {
            this.dDPVersionNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(testType.Item0)]
    public testType test {
        get {
            return this.testField;
        }
        set {
            this.testField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal schemaVersion {
        get {
            return this.schemaVersionField;
        }
        set {
            this.schemaVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="messageTypeType", Namespace="http://gisis.imo.org/XML/LRIT/receipt/2008")]
public enum messageTypeType3 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7")]
    Item7,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/receipt/2008")]
public enum receiptCodeType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7")]
    Item7,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("8")]
    Item8,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("9")]
    Item9,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/sarSurpicRequest/2008")]
public partial class SARSURPICType {
    
    private messageTypeType2 messageTypeField;
    
    private string messageIdField;
    
    private string itemField;
    
    private ItemChoiceType1 itemElementNameField;
    
    private string numberOfPositionsField;
    
    private string dataUserRequestorField;
    
    private System.DateTime timeStampField;
    
    private string dDPVersionNumField;
    
    private testType testField;
    
    private decimal schemaVersionField;
    
    public SARSURPICType() {
        this.testField = testType.Item0;
    }
    
    /// <remarks/>
    public messageTypeType2 MessageType {
        get {
            return this.messageTypeField;
        }
        set {
            this.messageTypeField = value;
        }
    }
    
    /// <remarks/>
    public string MessageId {
        get {
            return this.messageIdField;
        }
        set {
            this.messageIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SARCircularArea", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("SARRectangularArea", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType1 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string NumberOfPositions {
        get {
            return this.numberOfPositionsField;
        }
        set {
            this.numberOfPositionsField = value;
        }
    }
    
    /// <remarks/>
    public string DataUserRequestor {
        get {
            return this.dataUserRequestorField;
        }
        set {
            this.dataUserRequestorField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TimeStamp {
        get {
            return this.timeStampField;
        }
        set {
            this.timeStampField = value;
        }
    }
    
    /// <remarks/>
    public string DDPVersionNum {
        get {
            return this.dDPVersionNumField;
        }
        set {
            this.dDPVersionNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(testType.Item0)]
    public testType test {
        get {
            return this.testField;
        }
        set {
            this.testField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal schemaVersion {
        get {
            return this.schemaVersionField;
        }
        set {
            this.schemaVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="messageTypeType", Namespace="http://gisis.imo.org/XML/LRIT/sarSurpicRequest/2008")]
public enum messageTypeType2 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/sarSurpicRequest/2008", IncludeInSchema=false)]
public enum ItemChoiceType1 {
    
    /// <remarks/>
    SARCircularArea,
    
    /// <remarks/>
    SARRectangularArea,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/positionRequest/2008")]
public partial class requestDurationType {
    
    private System.DateTime startTimeField;
    
    private bool startTimeFieldSpecified;
    
    private System.DateTime stopTimeField;
    
    private bool stopTimeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime startTime {
        get {
            return this.startTimeField;
        }
        set {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startTimeSpecified {
        get {
            return this.startTimeFieldSpecified;
        }
        set {
            this.startTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime stopTime {
        get {
            return this.stopTimeField;
        }
        set {
            this.stopTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool stopTimeSpecified {
        get {
            return this.stopTimeFieldSpecified;
        }
        set {
            this.stopTimeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/positionRequest/2008")]
public partial class ShipPositionRequestType {
    
    private messageTypeType1 messageTypeField;
    
    private string messageIdField;
    
    private string iMONumField;
    
    private string dataUserProviderField;
    
    private accessTypeType accessTypeField;
    
    private string itemField;
    
    private ItemChoiceType itemElementNameField;
    
    private string distanceField;
    
    private requestTypeType requestTypeField;
    
    private requestDurationType requestDurationField;
    
    private string dataUserRequestorField;
    
    private System.DateTime timeStampField;
    
    private string dDPVersionNumField;
    
    private testType testField;
    
    private decimal schemaVersionField;
    
    public ShipPositionRequestType() {
        this.testField = testType.Item0;
    }
    
    /// <remarks/>
    public messageTypeType1 MessageType {
        get {
            return this.messageTypeField;
        }
        set {
            this.messageTypeField = value;
        }
    }
    
    /// <remarks/>
    public string MessageId {
        get {
            return this.messageIdField;
        }
        set {
            this.messageIdField = value;
        }
    }
    
    /// <remarks/>
    public string IMONum {
        get {
            return this.iMONumField;
        }
        set {
            this.iMONumField = value;
        }
    }
    
    /// <remarks/>
    public string DataUserProvider {
        get {
            return this.dataUserProviderField;
        }
        set {
            this.dataUserProviderField = value;
        }
    }
    
    /// <remarks/>
    public accessTypeType AccessType {
        get {
            return this.accessTypeField;
        }
        set {
            this.accessTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Place", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Port", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("PortFacility", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Distance {
        get {
            return this.distanceField;
        }
        set {
            this.distanceField = value;
        }
    }
    
    /// <remarks/>
    public requestTypeType RequestType {
        get {
            return this.requestTypeField;
        }
        set {
            this.requestTypeField = value;
        }
    }
    
    /// <remarks/>
    public requestDurationType RequestDuration {
        get {
            return this.requestDurationField;
        }
        set {
            this.requestDurationField = value;
        }
    }
    
    /// <remarks/>
    public string DataUserRequestor {
        get {
            return this.dataUserRequestorField;
        }
        set {
            this.dataUserRequestorField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TimeStamp {
        get {
            return this.timeStampField;
        }
        set {
            this.timeStampField = value;
        }
    }
    
    /// <remarks/>
    public string DDPVersionNum {
        get {
            return this.dDPVersionNumField;
        }
        set {
            this.dDPVersionNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(testType.Item0)]
    public testType test {
        get {
            return this.testField;
        }
        set {
            this.testField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal schemaVersion {
        get {
            return this.schemaVersionField;
        }
        set {
            this.schemaVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="messageTypeType", Namespace="http://gisis.imo.org/XML/LRIT/positionRequest/2008")]
public enum messageTypeType1 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/positionRequest/2008")]
public enum accessTypeType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/positionRequest/2008", IncludeInSchema=false)]
public enum ItemChoiceType {
    
    /// <remarks/>
    Place,
    
    /// <remarks/>
    Port,
    
    /// <remarks/>
    PortFacility,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/positionRequest/2008")]
public enum requestTypeType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7")]
    Item7,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("8")]
    Item8,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("9")]
    Item9,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("10")]
    Item10,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("11")]
    Item11,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gisis.imo.org/XML/LRIT/2008")]
public partial class Response {
    
    private responseType responseField;
    
    /// <remarks/>
    public responseType response {
        get {
            return this.responseField;
        }
        set {
            this.responseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gisis.imo.org/XML/LRIT/2008")]
public enum responseType {
    
    /// <remarks/>
    Success,
}
