USE [LRIT]
GO

/****** Object:  Table [dbo].[InvoiceCounter]    Script Date: 06/09/2011 20:39:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[InvoiceCounter](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nextInvoice] [bigint] NOT NULL,
 CONSTRAINT [PK_InvoiceCounter] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


